services:
  - type: web
    name: steam-hours-site
    runtime: node
    plan: free
    region: frankfurt
    repo: https://github.com/ignorantshopping7262/simple-steam-idler-replit
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: ACCOUNT_NAME
        value: "kryllih"
      - key: STEAM_SESSION_ID
        value: "afe1f8983374c87d0961b710"
      - key: STEAM_LOGIN_SECURE
        value: "76561199704306070%7C%7CeyAidHlwIjogIkpXVCIsICJhbGciOiAiRWREU0EiIH0.eyAiaXNzIjogInI6MDAwRV8yNzkxRUY4Ql80QUZENSIsICJzdWIiOiAiNzY1NjExOTk3MDQzMDYwNzAiLCAiYXVkIjogWyAid2ViOmNvbW11bml0eSIgXSwgImV4cCI6IDE3NzU5Mzg2MzgsICJuYmYiOiAxNzY3MjExNDUzLCAiaWF0IjogMTc3NTg1MTQ1MywgImp0aSI6ICIwMDEyXzI4MDA3NjY4XzE0QkM4IiwgIm9hdCI6IDE3Njg3Njk1MzMsICJydF9leHAiOiAxNzg2OTQ5NzYxLCAicGVyIjogMCwgImlwX3N1YmplY3QiOiAiOTIuMjUwLjI0LjE1MiIsICJpcF9jb25maXJtZXIiOiAiMTQ4LjY5LjE5OC4zMCIgfQ.zjhDyb53qnioPZvxqLMLCLW_hg0wWfWxpjIYIZqqVVcG9bMcfi6SprU_W_BNY12587nAmgHE8W8VGV2FGSDcAw"
      - key: APP_ID
        value: "734750"
